# Cloud Connectivity Binary Sensors
# Purpose: Monitor cloud and remote access status for GPT integration

- platform: template
  sensors:
    cloud_logged_in:
      friendly_name: "Cloud Logged In"
      value_template: >
        {{ is_state('binary_sensor.remote_ui', 'on') }}
      icon_template: >
        {% if is_state('binary_sensor.remote_ui', 'on') %}
          mdi:account-check
        {% else %}
          mdi:account-off
        {% endif %}

    gpt_access_available:
      friendly_name: "GPT Access Available"
      value_template: >
        {% set remote_ui = is_state('binary_sensor.remote_ui', 'on') %}
        {% set internet = is_state('binary_sensor.192_168_1_1', 'on') %}
        {{ remote_ui and internet }}
      icon_template: >
        {% set available = is_state('binary_sensor.gpt_access_available', 'on') %}
        {% if available %}
          mdi:robot-happy
        {% else %}
          mdi:robot-dead
        {% endif %}

    nabu_casa_healthy:
      friendly_name: "Nabu Casa Healthy"
      value_template: >
        {% set remote_ui = is_state('binary_sensor.remote_ui', 'on') %}
        {% set uptime = states('sensor.uptime') | int(0) %}
        {{ remote_ui and uptime > 300 }}
      icon_template: >
        {% if is_state('binary_sensor.nabu_casa_healthy', 'on') %}
          mdi:cloud-check
        {% else %}
          mdi:cloud-alert
        {% endif %}