# MQTT Connection Health Monitoring
# Binary sensor to track MQTT broker connectivity

- platform: template
  sensors:
    mqtt_connection:
      friendly_name: "MQTT Connection Status"
      device_class: connectivity
      value_template: >
        {% set last_update = states.binary_sensor | selectattr('entity_id', 'search', 'mqtt') | list | length %}
        {% if last_update > 0 %}
          {{ 'ON' if now() - states.sensor.uptime.last_changed < timedelta(minutes=5) else 'OFF' }}
        {% else %}
          OFF
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.mqtt_connection', 'on') %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}
    
    mqtt_broker_health:
      friendly_name: "MQTT Broker Health"
      device_class: connectivity
      value_template: >
        {% set uptime = states('sensor.uptime') | int(0) %}
        {{ uptime > 5 and states('sensor.uptime') != 'unavailable' }}
      icon_template: >
        {% if is_state('binary_sensor.mqtt_broker_health', 'on') %}
          mdi:server-network
        {% else %}
          mdi:server-network-off
        {% endif %}
      availability_template: >
        {{ states('sensor.uptime') != 'unavailable' }}