- alias: Ensure GPT Status File Permissions
  id: ensure_gpt_status_file_permissions
  description: Checks and repairs permissions on gpt_status.txt to prevent sync failures.
  mode: single
  trigger:
    - platform: time
      at: "03:00:00"
  action:
    - service: shell_command.fix_gpt_status_permissions
