# Enhanced Boiler Usage Detection with Z2M Data
# Rich sensor data from migrated Aqara devices

binary_sensor:
  - platform: template
    sensors:
      heating_demand_active:
        friendly_name: "Heating Demand Active"
        device_class: heat
        value_template: >
          {# Enhanced heating demand detection with Z2M data #}
          {% set trv_demand = false %}
          {% set vibration_demand = false %}
          {% set thermostat_vib = false %}

          {# TRV position check (Z2M provides real position data) #}
          {% if states('sensor.lounge_trv_position') | int(0) > 10 or
                states('sensor.bedroom_trv_position') | int(0) > 10 %}
            {% set trv_demand = true %}
          {% endif %}

          {# Vibration sensor check (Z2M provides angle/intensity data) #}
          {% set angle_x = states('sensor.aqara_vibration_sensor_angle_x') | float(0) %}
          {% set angle_y = states('sensor.aqara_vibration_sensor_angle_y') | float(0) %}
          {% set angle_z = states('sensor.aqara_vibration_sensor_angle_z') | float(0) %}
          {% if (angle_x | abs) > 15 or (angle_y | abs) > 15 or (angle_z | abs) > 15 %}
            {% set vibration_demand = true %}
          {% endif %}

          {# Thermostat vibration check (if sensors added) #}
          {% if states('binary_sensor.thermostat_upstairs_vibration_occupancy') == 'on' or
                states('binary_sensor.thermostat_downstairs_vibration_occupancy') == 'on' %}
            {% set thermostat_vib = true %}
          {% endif %}

          {# Return true if any heating demand detected #}
          {{ trv_demand or vibration_demand or thermostat_vib or
             is_state('climate.lounge', 'heat') or is_state('climate.bedroom', 'heat') }}

sensor:
  - platform: template
    sensors:
      boiler_hot_water_flow:
        friendly_name: "Boiler Hot Water Flow"
        unit_of_measurement: "L/min"
        icon_template: mdi:water-pump
        value_template: >
          {# Priority: Use actual flow sensor if available #}
          {% if states('sensor.hot_water_flow_rate') not in ['unknown', 'unavailable', ''] %}
            {{ states('sensor.hot_water_flow_rate') | float(0) }}
          {% elif states('sensor.hot_water_flow') not in ['unknown', 'unavailable', ''] %}
            {{ states('sensor.hot_water_flow') | float(0) }}
          {% else %}
            {# Fallback: Estimate based on short cycles without heating demand #}
            {% if is_state('input_boolean.boiler_running_status', 'on') %}
              {% set start_time = states('input_datetime.boiler_last_start') %}
              {% if start_time not in ['unknown', 'unavailable', ''] %}
                {% set start = strptime(start_time, '%Y-%m-%d %H:%M:%S') %}
                {% set duration = (now() - start).total_seconds() %}
                {# Assume hot water if cycle < 5 minutes and no heating demand #}
                {% if duration < 300 and not is_state('binary_sensor.heating_demand_active', 'on') %}
                  8.5  {# Typical shower flow rate #}
                {% else %}
                  0
                {% endif %}
              {% else %}
                0
              {% endif %}
            {% else %}
              0
            {% endif %}
          {% endif %}

      boiler_hot_water_runtime_today:
        friendly_name: "Boiler Hot Water Runtime Today"
        unit_of_measurement: 'h'
        icon_template: mdi:water-pump
        value_template: >
          {% set total_runtime = states('sensor.boiler_runtime_today') | float(0) %}
          {% set heating_runtime = states('sensor.boiler_heating_runtime_today') | float(0) %}
          {{ (total_runtime - heating_runtime) | round(2) }}

      # Z2M TRV Position Sensors (real data from migrated devices)
      lounge_trv_position:
        friendly_name: "Lounge TRV Position"
        unit_of_measurement: "%"
        icon_template: mdi:valve
        value_template: "{{ states('sensor.lounge_trv_position') | int(0) }}"

      bedroom_trv_position:
        friendly_name: "Bedroom TRV Position"
        unit_of_measurement: "%"
        icon_template: mdi:valve
        value_template: "{{ states('sensor.bedroom_trv_position') | int(0) }}"

      # Legacy placeholders (will be removed after migration)
      trv_office_position:
        friendly_name: "TRV Office Position (Legacy)"
        unit_of_measurement: "%"
        icon_template: mdi:radiator-disabled
        value_template: "{{ 0 }}"

      trv_bathroom_position:
        friendly_name: "TRV Bathroom Position (Legacy)"
        unit_of_measurement: "%"
        icon_template: mdi:radiator-disabled
        value_template: "{{ 0 }}"

      trv_dining_position:
        friendly_name: "TRV Dining Position (Legacy)"
        unit_of_measurement: "%"
        icon_template: mdi:radiator-disabled
        value_template: "{{ 0 }}"

      trv_kitchen_position:
        friendly_name: "TRV Kitchen Position (Legacy)"
        unit_of_measurement: "%"
        icon_template: mdi:radiator-disabled
        value_template: "{{ 0 }}"