- alias: Notify System Update Available
  id: notify_system_update_available
  trigger:
    - platform: state
      entity_id:
        - update.home_assistant_supervisor_update
        - update.home_assistant_core_update
        - update.matter_server_update
        - update.samba_share_update
        - update.advanced_ssh_web_terminal_update
        - update.mosquitto_broker_update
        - update.file_editor_update
        - update.govee_to_mqtt_bridge_update
        - update.home_assistant_operating_system_update
      to: "on"
  action:
    - service: notify.notify
      data:
        message: "A system update is available for Home Assistant."

- alias: Notify Backup Created
  id: notify_backup_created
  trigger:
    - platform: event
      event_type: backup_automatic_backup
  action:
    - service: notify.mobile_app_plop
      data:
        message: "A new automatic backup has been created at {{ now().strftime('%Y-%m-%d %H:%M:%S') }}."

- alias: Backup Success Reminder
  id: backup_success_reminder
  trigger:
    - platform: time_pattern
      hours: 0
      minutes: 0
      seconds: 0
  condition:
    - condition: template
      value_template: >
        {{ (now() - states('sensor.backup_last_successful_automatic_backup') | as_timestamp) > (7 * 86400) }}
  action:
    - service: notify.notify
      data:
        message: "It has been more than 7 days since the last successful backup."

- alias: Notify of Stale Updates
  id: notify_of_stale_updates
  trigger:
    - platform: time_pattern
      hours: "/1"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: update.home_assistant_supervisor_update
          state: "off"
        - condition: state
          entity_id: update.home_assistant_core_update
          state: "off"
  action:
    - service: notify.mobile_app_plop
      data:
        message: "One or more updates have been inactive for a while. Please check!"

- alias: ESP Offline Alert
  id: esp_offline_alert
  trigger:
    - platform: state
      entity_id: binary_sensor.esp_device_status
      to: "off"
      for: "00:05:00"
  action:
    - service: notify.mobile_app_plop
      data:
        title: "ESP Device Offline"
        message: "Your ESP device has been unreachable for over 5 minutes. Check WiFi, power, or mDNS."

- alias: Log ESP Restart Reason (Notifications)
  id: log_esp_restart_reason_notify
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.persistent_notification
      data:
        message: "ESP restarted due to: {{ states('sensor.esp_restart_reason') }}"

- alias: Alert if JIT Plugin goes offline
  id: alert_if_jit_plugin_goes_offline
  trigger:
    - platform: state
      entity_id: binary_sensor.jit_plugin_flask_online
      to: "off"
      for: "00:01:00"
  action:
    - service: notify.mobile_app_plop
      data:
        title: "🚨 JIT Plugin Offline"
        message: "Flask server is unreachable at port 5001."

- alias: Alert if WSL Restart Marker Missing (Notifications)
  id: alert_if_wsl_restart_marker_missing_notify
  trigger:
    - platform: state
      entity_id: sensor.wsl_startup_marker
      to: "Missing"
      for: "00:05:00"
  action:
    - service: persistent_notification.create
      data:
        title: "⚠️ WSL Startup Not Detected"
        message: "The Flask startup script may not have run. Please run run_flask_hardened.sh manually."
    - service: notify.mobile_app_yourdevice
      data:
        title: "🛑 JIT Plugin Not Auto-Launched"
        message: "WSL Flask marker not found — check Flask server."

- alias: Announce GPT reply
  id: announce_gpt_reply
  trigger:
    - platform: state
      entity_id: input_text.gpt_result_core
  action:
    - service: notify.mobile_app_plop
      data:
        message: "{{ states('input_text.gpt_result_core') }}"
        type: tts

- alias: Push GPT reply to mobile
  id: push_gpt_reply_to_mobile
  trigger:
    - platform: state
      entity_id: input_text.gpt_result_core
  action:
    - service: notify.mobile_app_plop
      data:
        message: "{{ states('input_text.gpt_result_core') }}"
