# Weekly Digest Automation for AI Monitoring

automation:
  - alias: "Weekly Digest Trigger"
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: shell_command.run_weekly_digest
