# ADS-B Enhanced Sensors for Flight Radar Dashboard
# Adds telemetry, proximity alerts, and signal monitoring

- platform: template
  sensors:
    # Proximity Alert System
    aircraft_proximity_alert:
      friendly_name: "Aircraft Proximity Alert"
      value_template: >
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {% for f in flights %}
            {% if f.distance and f.distance < 5 %}
              on
            {% endif %}
          {% endfor %}
        {% endif %}
        off
      icon_template: >
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% set has_close = false %}
        {% if flights %}
          {% for f in flights %}
            {% if f.distance and f.distance < 5 %}
              {% set has_close = true %}
            {% endif %}
          {% endfor %}
        {% endif %}
        {% if has_close %}
          mdi:airplane-alert
        {% else %}
          mdi:airplane
        {% endif %}

    # ADS-B Signal Strength (RSSI) - placeholder for actual receiver data
    adsb_signal_strength:
      friendly_name: "ADS-B Signal Strength"
      unit_of_measurement: "dBm"
      value_template: >
        {% set aircraft_count = states('sensor.flightradar24_current_in_area') | int(0) %}
        {% if aircraft_count > 10 %}
          -45
        {% elif aircraft_count > 5 %}
          -55
        {% elif aircraft_count > 0 %}
          -65
        {% else %}
          -85
        {% endif %}
      icon_template: mdi:signal

    # Vertical Rate Tracking
    aircraft_vertical_rate:
      friendly_name: "Aircraft Vertical Rate"
      unit_of_measurement: "ft/min"
      value_template: >
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {% set rates = [] %}
          {% for f in flights %}
            {% if f.get('vertical_rate') is not none %}
              {% set rates = rates + [f.get('vertical_rate')] %}
            {% endif %}
          {% endfor %}
          {% if rates %}
            {{ rates | max }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      icon_template: >
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% set max_rate = 0 %}
        {% if flights %}
          {% for f in flights %}
            {% if f.get('vertical_rate') is not none and f.get('vertical_rate') > max_rate %}
              {% set max_rate = f.get('vertical_rate') %}
            {% endif %}
          {% endfor %}
        {% endif %}
        {% if max_rate > 1000 %}
          mdi:airplane-takeoff
        {% elif max_rate < -1000 %}
          mdi:airplane-landing
        {% else %}
          mdi:airplane-clock
        {% endif %}

    # ADS-B Receiver Status
    adsb_receiver_status:
      friendly_name: "ADS-B Receiver Status"
      value_template: >
        {% set signal = states('sensor.adsb_signal_strength') | int(-100) %}
        {% set aircraft = states('sensor.flightradar24_current_in_area') | int(0) %}
        {% if signal > -60 and aircraft > 0 %}
          Excellent
        {% elif signal > -70 and aircraft > 0 %}
          Good
        {% elif signal > -80 %}
          Fair
        {% elif signal > -90 %}
          Poor
        {% else %}
          No Signal
        {% endif %}
      icon_template: >
        {% set signal = states('sensor.adsb_signal_strength') | int(-100) %}
        {% set aircraft = states('sensor.flightradar24_current_in_area') | int(0) %}
        {% if signal > -60 and aircraft > 0 %}
          mdi:signal-cellular-3
        {% elif signal > -70 and aircraft > 0 %}
          mdi:signal-cellular-2
        {% elif signal > -80 %}
          mdi:signal-cellular-1
        {% else %}
          mdi:signal-cellular-outline
        {% endif %}

    # Closest Aircraft Distance
    closest_aircraft_distance:
      friendly_name: "Closest Aircraft Distance"
      unit_of_measurement: "km"
      value_template: >
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {% set distances = [] %}
          {% for f in flights %}
            {% if f.distance %}
              {% set distances = distances + [f.distance] %}
            {% endif %}
          {% endfor %}
          {% if distances %}
            {{ distances | min | round(1) }}
          {% else %}
            999
          {% endif %}
        {% else %}
          999
        {% endif %}
      icon_template: mdi:map-marker-distance

    # Aircraft Speed Average
    aircraft_average_speed:
      friendly_name: "Aircraft Average Speed"
      unit_of_measurement: "kts"
      value_template: >
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {% set speeds = [] %}
          {% for f in flights %}
            {% if f.get('velocity') is not none %}
              {% set speeds = speeds + [f.get('velocity')] %}
            {% endif %}
          {% endfor %}
          {% if speeds %}
            {{ (speeds | sum / speeds | length) | round(0) }}
          {% else %}
            0
          {% endif %}
        {% else %}
          0
        {% endif %}
      icon_template: mdi:speedometer

    # Flight Activity Trend
    flight_activity_trend:
      friendly_name: "Flight Activity Trend"
      value_template: >
        {% set current = states('sensor.flightradar24_current_in_area') | int(0) %}
        {% set entered = states('sensor.flightradar24_entered_area') | int(0) %}
        {% set exited = states('sensor.flightradar24_exited_area') | int(0) %}
        {% if entered > exited %}
          Increasing
        {% elif exited > entered %}
          Decreasing
        {% else %}
          Stable
        {% endif %}
      icon_template: >
        {% set current = states('sensor.flightradar24_current_in_area') | int(0) %}
        {% set entered = states('sensor.flightradar24_entered_area') | int(0) %}
        {% set exited = states('sensor.flightradar24_exited_area') | int(0) %}
        {% if entered > exited %}
          mdi:trending-up
        {% elif exited > entered %}
          mdi:trending-down
        {% else %}
          mdi:trending-neutral
        {% endif %}