# API Call Tracking Command Line Sensor
# Simulates VSCode extension API activity

- platform: command_line
  name: last_api_call_vscode
  command: 'date +%s'  # Returns current timestamp
  scan_interval: 60  # Increased from 30 to 60 seconds for performance
  value_template: "{{ value | int(0) }}"
  
# API Call Tracking Command Line Sensor
# Simulates VSCode extension API activity

- platform: command_line
  name: last_api_call_vscode
  command: 'date +%s'  # Returns current timestamp
  scan_interval: 60  # Increased from 30 to 60 seconds for performance
  value_template: "{{ value | int(0) }}"

# Template sensors moved to includes/templates/api_call_tracking.yaml
# Converted to modern template: sensor format to resolve HA repairs deprecation warnings