- platform: template
  sensors:
    integration_health_mqtt:
      friendly_name: "MQTT Integration Health"
      value_template: >
        {% if is_state('binary_sensor.mqtt_broker_online', 'on') %}
          Healthy
        {% else %}
          Offline
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.mqtt_broker_online', 'on') %}
          mdi:check-circle
        {% else %}
          mdi:alert-circle
        {% endif %}

    integration_health_adguard:
      friendly_name: "AdGuard Integration Health"
      value_template: >
        {% if is_state('binary_sensor.adguard_running', 'on') %}
          Healthy
        {% else %}
          Offline
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.adguard_running', 'on') %}
          mdi:shield-check
        {% else %}
          mdi:shield-alert
        {% endif %}

    integration_health_unifi:
      friendly_name: "UniFi Integration Health"
      value_template: >
        {% if is_state('binary_sensor.unifi_controller_online', 'on') %}
          Healthy
        {% else %}
          Offline
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.unifi_controller_online', 'on') %}
          mdi:wifi
        {% else %}
          mdi:wifi-off
        {% endif %}

    integration_health_hacs:
      friendly_name: "HACS Integration Health"
      value_template: >
        {% if is_state('binary_sensor.hacs_update_available', 'off') %}
          Healthy
        {% else %}
          Updates Available
        {% endif %}
      icon_template: >
        {% if is_state('binary_sensor.hacs_update_available', 'off') %}
          mdi:package-variant
        {% else %}
          mdi:package-up
        {% endif %}

    mqtt_broker_status:
      friendly_name: "MQTT Broker Status"
      value_template: >
        {% if states('sensor.mqtt_connected_devices') | int(0) > 0 %}
          {{ states('sensor.mqtt_connected_devices') }} devices connected
        {% else %}
          No devices
        {% endif %}
      icon_template: mdi:message-processing

    adguard_queries_blocked:
      friendly_name: "AdGuard Queries Blocked"
      value_template: >
        {% set blocked = states('sensor.adguard_dns_queries_blocked_ratio') | float(0) %}
        {{ (blocked * 100) | round(1) }}% blocked
      icon_template: mdi:shield

    unifi_controller_status:
      friendly_name: "UniFi Controller Status"
      value_template: >
        {% if states('sensor.unifi_connected_devices') | int(0) > 0 %}
          {{ states('sensor.unifi_connected_devices') }} devices
        {% else %}
          Offline
        {% endif %}
      icon_template: mdi:access-point-network

    hacs_installed_count:
      friendly_name: "HACS Installed Count"
      value_template: >
        {% set total = integration_entities('hacs') | length %}
        {{ total }} components
      icon_template: mdi:package-variant-closed