- platform: template
  sensors:
    adsb_feed_alive_status:
      friendly_name: "ADS-B Feed Alive"
      value_template: >
        {% if is_state('sensor.adsb_heartbeat', 'alive') %}
          OK
        {% else %}
          STALE
        {% endif %}
      icon_template: >
        {% if is_state('sensor.adsb_heartbeat', 'alive') %}
          mdi:airplane
        {% else %}
          mdi:alert
        {% endif %}

    health_monitor_alive_status:
      friendly_name: "Health Monitor Alive"
      value_template: >
        {% if is_state('sensor.health_monitor_status', 'alive') %}
          OK
        {% else %}
          STALE
        {% endif %}
      icon_template: >
        {% if is_state('sensor.health_monitor_status', 'alive') %}
          mdi:heart-pulse
        {% else %}
          mdi:alert
        {% endif %}
