# 📊 Zigbee Network Health Monitoring Sensors
# Purpose: Track mesh health, routing efficiency, and device status
# Created: 2025-11-06 by VSCode Mesh Surgery Protocol

- platform: mqtt
  name: "Zigbee Network Health"
  state_topic: "homeassistant/zigbee_audit/network_summary"
  value_template: >
    {% set data = value_json %}
    {% set total = data.total_devices | int(0) %}
    {% set misrouted = data.misrouted_count | int(0) %}
    {% if total > 0 %}
      {% set efficiency = ((total - misrouted) / total * 100) | round(1) %}
      {% if efficiency >= 90 %}Excellent ({{ efficiency }}%)
      {% elif efficiency >= 80 %}Good ({{ efficiency }}%)
      {% elif efficiency >= 70 %}Fair ({{ efficiency }}%)
      {% elif efficiency >= 60 %}Poor ({{ efficiency }}%)
      {% else %}Critical ({{ efficiency }}%)
      {% endif %}
    {% else %}Unknown
    {% endif %}
  json_attributes_topic: "homeassistant/zigbee_audit/network_summary"
  icon: mdi:zigbee

- platform: mqtt
  name: "Zigbee Coordinator Load"
  state_topic: "homeassistant/zigbee_audit/network_summary"
  value_template: "{{ value_json.coordinator_load | int(0) }}"
  unit_of_measurement: "devices"
  icon: mdi:router-wireless

- platform: mqtt
  name: "Zigbee Active Routers"
  state_topic: "homeassistant/zigbee_audit/network_summary"
  value_template: "{{ value_json.routers | int(0) }}"
  unit_of_measurement: "routers"
  icon: mdi:router-network

- platform: mqtt
  name: "Zigbee End Devices"
  state_topic: "homeassistant/zigbee_audit/network_summary"
  value_template: "{{ value_json.end_devices | int(0) }}"
  unit_of_measurement: "devices"
  icon: mdi:devices

- platform: mqtt
  name: "Zigbee Misrouted Devices"
  state_topic: "homeassistant/zigbee_audit/network_summary"
  value_template: "{{ value_json.misrouted_count | int(0) }}"
  unit_of_measurement: "devices"
  icon: mdi:alert-circle

# Zigbee Network Health Template Sensors - CONVERTED TO MODERN TEMPLATE FORMAT
# Template sensors moved to includes/templates/zigbee_network_health.yaml
# Converted: 5 template sensors (zigbee_mesh_efficiency, zigbee_last_rebalance, zigbee_rebalance_status, zigbee_z2_router_load, zigbee_z3_router_load)
# Conversion completed: 2026-01-06